import test from 'node:test';
import assert from 'node:assert/strict';
import {createCalendarAuthHandler} from './calendar-auth-http.mjs';
function fixture(readOnly=false){
 const calls=[],headers={},res={setHeader:(k,v)=>headers[k]=v};let result;
 const handler=createCalendarAuthHandler({basePath:'/hub/modules/live',readOnly,json:(_,status,body)=>result={status,body},reader:{status:async()=>({authorized:false}),begin:()=>{calls.push('begin');return {state:'opaque',url:'https://accounts.feishu.cn/authorize'};},complete:async args=>{calls.push(args);return {authorized:true};}}});
 return {calls,headers,async run(path,method='GET',auth={ok:true,permissions:{super_admin:true}},extra={}){await handler({method,headers:{host:'example.com',...extra}},res,new URL('https://example.com'+path+'?code=code&state=state'),path,auth);return result;}};
}
test('内部标记或普通成员不能获得授权入口，授权管理仅原管理员可见',async()=>{const f=fixture();for(const auth of [{ok:true,internal:true},{ok:true,permissions:{}},{ok:false,permissions:{super_admin:true}}])assert.equal((await f.run('/api/lifecycle/calendar-auth/start','POST',auth,{'x-requested-with':'XMLHttpRequest'})).status,403);assert.equal(f.calls.length,0);});
test('只读候选不保存或发起日历授权',async()=>{const f=fixture(true);assert.equal((await f.run('/api/lifecycle/calendar-auth/start','POST',undefined,{'x-requested-with':'XMLHttpRequest'})).status,423);assert.equal((await f.run('/api/lifecycle/calendar-auth/callback')).status,423);assert.equal(f.calls.length,0);});
test('发起授权拒绝跨站且正确 Cookie 为安全定域回调路径',async()=>{const f=fixture();assert.equal((await f.run('/api/lifecycle/calendar-auth/start','POST',undefined,{'x-requested-with':'XMLHttpRequest',origin:'https://evil.test'})).status,403);assert.equal((await f.run('/api/lifecycle/calendar-auth/start','POST',undefined,{'x-requested-with':'XMLHttpRequest','sec-fetch-site':'cross-site'})).status,403);assert.equal((await f.run('/api/lifecycle/calendar-auth/start','POST',undefined,{'x-requested-with':'XMLHttpRequest',origin:'https://example.com'})).status,200);assert.match(f.headers['Set-Cookie'],/Path=\/hub\/modules\/live\/api\/lifecycle\/calendar-auth\/callback; HttpOnly; Secure; SameSite=Lax/);});
test('回调只交给状态校验读取器，不要求跨站跳转带 OA，不泄漏凭据',async()=>{const f=fixture();const r=await f.run('/api/lifecycle/calendar-auth/callback','GET',null,{cookie:'live_calendar_oauth_state=bound'});assert.equal(r.status,200);assert.deepEqual(f.calls[0],{code:'code',state:'state',cookieState:'bound'});assert.doesNotMatch(JSON.stringify(r.body),/access_token|refresh_token|code=code/);assert.match(f.headers['Set-Cookie'],/Max-Age=0/);});
