import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';

// Code-only fixture: no server listener, network, credential file or grant store.
const PIN='3a690ac446695c02c650ac07811f24db789673a0ab41604735a6a7006045e679';
const ORIGINAL_PIN='0b37fd54a6feeb5fc277a10da5168bbac7ac6980a61eb49de1e489495f452f74';
function sourcePath(fileName, envFile, envSha, fallback){
  const suppliedFile=process.env[envFile],suppliedSha=process.env[envSha];
  if(Boolean(suppliedFile)!==Boolean(suppliedSha))throw new Error('explicit source path and SHA must be paired');
  const path=suppliedFile||fileURLToPath(new URL(fallback,import.meta.url));
  const expected=suppliedSha||fileName;
  if(!/^[a-f0-9]{64}$/u.test(expected))throw new Error('invalid source pin');
  const bytes=readFileSync(path),sha=createHash('sha256').update(bytes).digest('hex');
  if(sha!==expected)throw new Error('source pin mismatch');
  return {path,bytes,sha};
}
const candidate=sourcePath(PIN,'WIS_PRIVATE_HTTP_MODULE','WIS_PRIVATE_HTTP_SHA','../private-auth-hold-exact-20260929-0245/candidate/private-chat-auth.mjs');
const original=sourcePath(ORIGINAL_PIN,'WIS_PRIVATE_HTTP_ORIGINAL','WIS_PRIVATE_HTTP_ORIGINAL_SHA','../private-auth-hold-exact-20260929-0245/reference/private-chat-auth.mjs');
const {createPrivateChatAuth}=await import('data:text/javascript;base64,'+candidate.bytes.toString('base64'));
const {createPrivateChatAuth:oldFactory}=await import('data:text/javascript;base64,'+original.bytes.toString('base64'));
const prefix='/api/lifecycle/private-chat-auth/',origin='https://oa.synthetic.invalid',basePath='/live',NOW=1780000000000;
const secret='SYNTHETIC_PRIVATE_SECRET_ONLY';
const normal=(authorized=false)=>({configured:true,authorized,status:authorized?'authorized':'unauthorized',recoveryRequired:false,retryAllowed:true});
const held=()=>({configured:true,authorized:false,status:'recovery_required',recoveryRequired:true,retryAllowed:false});
const busy=()=>({configured:true,authorized:false,status:'busy',recoveryRequired:false,retryAllowed:false});
const unconfigured=()=>({configured:false,authorized:false,status:'unconfigured',recoveryRequired:false,retryAllowed:false});
const defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject};};
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const res=()=>({headers:{},jsonCalls:0,endCalls:0,setHeader(name,value){this.headers[name]=value;},writeHead(status,headers){this.status=status;Object.assign(this.headers,headers);},end(body){this.endCalls++;this.html=body;}});
const req=(method='POST',headers={})=>({method,headers:{origin,'x-requested-with':'XMLHttpRequest','sec-fetch-site':'same-origin',...headers}});
function fixture(options={},factory=createPrivateChatAuth){
  const ctx={counts:{actor:0,status:0,begin:0,complete:0,verify:0,other:0},number:'2001',at:NOW,
    states:{'2001':normal(),'2002':normal()},hooks:{},verifiedActors:[]};
  const actors={'2001':{name:'倪梦萍',openId:'ou_toy_n',peerOpenId:'ou_toy_l'},'2002':{name:'刘慧迅',openId:'ou_toy_l',peerOpenId:'ou_toy_n'}};
  const readers={};
  for(const number of Object.keys(actors))readers[number]={
    async status(){ctx.counts.status++;return ctx.hooks.status?ctx.hooks.status(number):ctx.states[number];},
    begin(){ctx.counts.begin++;if(ctx.hooks.begin)return ctx.hooks.begin(number);const state='pchat_toy_'+number+'_'+ctx.counts.begin;return {state,url:'https://accounts.feishu.cn/open-apis/authen/v1/authorize?state='+state};},
    async complete(input){ctx.counts.complete++;ctx.completeInput=input;if(ctx.hooks.complete)return ctx.hooks.complete(input,number);ctx.states[number]=normal(true);return normal(true);},
    async verify(){ctx.counts.verify++;return ctx.hooks.verify?ctx.hooks.verify(number):{verified:true,sampleAvailable:false};},
  };
  const auth=(number='2001')=>({ok:true,mode:'central',user:{number,name:actors[number]?.name,open_id:actors[number]?.openId}});
  const wrapper=factory({actors,readers,basePath,publicOrigin:origin,enabled:true,
    json(response,status,body){response.status=status;response.body=body;response.jsonCalls++;},
    async verifyActor(actor){ctx.counts.actor++;ctx.verifiedActors.push(actor);return ctx.hooks.actor?ctx.hooks.actor(actor):true;},
    clock:()=>ctx.at,...options});
  const api=async(action='start',authorization=auth(),request=req())=>{const response=res();await wrapper.handleApi(request,response,prefix+action,authorization);return response;};
  const callback=async(state,params={},request=req('GET',{cookie:'live_private_chat_oauth_state='+state}))=>{const response=res();const url=new URL(origin+basePath+'/api/lifecycle/calendar-auth/callback');url.searchParams.set('state',state);url.searchParams.set('code','toy_code');for(const [key,value]of Object.entries(params))url.searchParams.set(key,value);response.handled=await wrapper.handleCallback(request,response,url);return response;};
  return {ctx,actors,readers,wrapper,auth,api,callback};
}
function noStart(f,response){assert.equal(f.ctx.counts.begin,0);assert.equal(f.ctx.counts.verify,0);assert.equal(f.ctx.counts.complete,0);assert.equal(response.headers['Set-Cookie'],undefined);assert.equal(response.body?.authorizeUrl,undefined);assert.notEqual(response.body?.ok,true);}
function noSecret(response){assert.equal(JSON.stringify(response.body||{}).includes(secret),false);assert.equal(String(response.html||'').includes(secret),false);}
function assertBlocked(response,kind='held'){assert.equal(response.status,409);assert.equal(response.body?.ok,false);assert.equal(response.body?.retryAllowed,false);assert.equal(response.body?.code,'private_chat_authorization_'+kind);assert.equal(response.body?.status,kind==='held'?'recovery_required':'busy');}
async function begin(f,number='2001'){const started=await f.api('start',f.auth(number));assert.equal(started.status,200);return new URL(started.body.authorizeUrl).searchParams.get('state');}

test('candidate and original full bytes have explicit independent pins',()=>{assert.equal(candidate.sha,PIN);assert.equal(original.sha,ORIGINAL_PIN);});
test('original page CSP, escaped markup, cookies and cache helper bytes remain exact',()=>{
  const old=original.bytes.toString(),now=candidate.bytes.toString();
  for(const [start,end]of [['  function page(', '\n  async function handleApi('],['  const cookie=', '\n  // Check']]){
    const oldRange=old.slice(old.indexOf(start),old.indexOf(end,old.indexOf(start)));
    const actual=start.includes('page')?now.slice(now.indexOf(start),now.indexOf('\n  async function callbackFailure(',now.indexOf(start))):now.slice(now.indexOf(start),now.indexOf('\n  function validOrigin(',now.indexOf(start)));
    assert.equal(actual,oldRange);
  }
});
test('normal OA start keeps exact cookie security and official redirect',async()=>{const f=fixture(),r=await f.api();assert.equal(r.status,200);assert.equal(f.ctx.counts.begin,1);assert.match(r.headers['Set-Cookie'],/Max-Age=600; Path=\/live\/api\/lifecycle\/calendar-auth\/callback; HttpOnly; Secure; SameSite=Lax$/u);assert.equal(new URL(r.body.authorizeUrl).hostname,'accounts.feishu.cn');assert.equal(r.headers['Cache-Control'],'no-store');assert.equal(r.headers['Referrer-Policy'],'no-referrer');});
test('normal central missing open_id and missing degraded remains compatible',async()=>{const f=fixture(),a=f.auth();delete a.user.open_id;const r=await f.api('start',a);assert.equal(r.status,200);assert.equal(f.ctx.counts.begin,1);assert.equal(f.ctx.verifiedActors[0].openId,'ou_toy_n');});
test('realName alone plus strict degraded false remains compatible',async()=>{const f=fixture(),a=f.auth();a.user.realName=a.user.name;delete a.user.name;a.degraded=false;assert.equal((await f.api('start',a)).status,200);});
test('both correct name fields are allowed',async()=>{const f=fixture(),a=f.auth();a.user.realName=a.user.name;assert.equal((await f.api('start',a)).status,200);});

const badAuthCases=[
  ['ok string',a=>{a.ok='true';}],['ok 1',a=>{a.ok=1;}],['ok false',a=>{a.ok=false;}],['noncentral',a=>{a.mode='local';}],
  ['degraded true',a=>{a.degraded=true;}],['degraded null',a=>{a.degraded=null;}],['degraded zero',a=>{a.degraded=0;}],['degraded string',a=>{a.degraded='false';}],
  ['name mismatch',a=>{a.user.name='另一个合成人';}],['realName mismatch',a=>{a.user.realName='另一个合成人';}],['name null',a=>{a.user.name=null;}],['no names',a=>{delete a.user.name;}],
  ['number numeric',a=>{a.user.number=2001;}],['number prototype',a=>{a.user.number='toString';}],['number mismatch',a=>{a.user.number='0000';}],
  ['openid mismatch',a=>{a.user.open_id='ou_other';}],['openid object',a=>{a.user.open_id={toString:()=>secret};}],['openid false',a=>{a.user.open_id=false;}],['openid empty',a=>{a.user.open_id='';}],
  ['name accessor',a=>{Object.defineProperty(a.user,'name',{get(){throw new Error(secret);}});}],['openid accessor',a=>{Object.defineProperty(a.user,'open_id',{get(){throw new Error(secret);}});}],
  ['inherited name',a=>{delete a.user.name;Object.setPrototypeOf(a.user,{name:'倪梦萍'});}],['inherited openid',a=>{delete a.user.open_id;Object.setPrototypeOf(a.user,{open_id:'ou_toy_n'});}],
];
for(const [label,mutate]of badAuthCases)test('identity failclosed: '+label,async()=>{const f=fixture(),a=f.auth();mutate(a);const r=await f.api('start',a);assert.equal(r.status,403);noStart(f,r);assert.equal(f.ctx.counts.actor,0);noSecret(r);});
test('configuration actors and reader methods cannot be retargeted after creation',async()=>{const f=fixture();f.actors['2001'].openId='ou_evil';f.actors['2001'].peerOpenId='ou_evil_peer';f.actors['2001'].name='另一个合成人';f.readers['2001'].begin=()=>{f.ctx.counts.other++;throw new Error(secret);};const a={ok:true,mode:'central',user:{number:'2001',name:'倪梦萍',open_id:'ou_toy_n'}};const r=await f.api('start',a);assert.equal(r.status,200);assert.equal(f.ctx.counts.other,0);assert.equal(f.ctx.verifiedActors[0].peerOpenId,'ou_toy_l');assert.equal(Object.isFrozen(f.ctx.verifiedActors[0]),true);});
test('maps themselves cannot replace callback reader or actor',async()=>{const f=fixture(),state=await begin(f);f.actors['2001']={name:'另一个合成人',openId:'ou_other',peerOpenId:'ou_pair'};f.readers['2001']={complete(){f.ctx.counts.other++;}};const r=await f.callback(state);assert.equal(r.status,200);assert.equal(f.ctx.counts.complete,1);assert.equal(f.ctx.counts.other,0);assert.match(r.html,/倪梦萍/u);});
test('ineligible status does not probe reader or source',async()=>{const f=fixture(),r=await f.api('status',{ok:false},req('GET'));assert.equal(r.status,200);assert.equal(r.body.eligible,false);assert.equal(f.ctx.counts.status,0);assert.equal(f.ctx.counts.actor,0);});

for(const [label,request,options,status]of [
  ['start GET',req('GET'),{},405],['entry OFF',req(),{enabled:false},423],['entry truthy is not enabled',req(),{enabled:'true'},423],
  ['wrong origin',req('POST',{origin:'https://other.invalid'}),{},403],['cross site',req('POST',{'sec-fetch-site':'cross-site'}),{},403],
  ['wrong XRequested',req('POST',{'x-requested-with':'other'}),{},403],['canonical URL not origin',req(),{publicOrigin:origin+'/path'},403],
  ['canonical http',req(),{publicOrigin:'http://oa.synthetic.invalid'},403],['canonical userinfo',req(),{publicOrigin:'https://name:pass@oa.synthetic.invalid'},403],
])test('preserved method/enabled/CSRF gate: '+label,async()=>{const f=fixture(options),r=await f.api('start',f.auth(),request);assert.equal(r.status,status);noStart(f,r);assert.equal(f.ctx.counts.actor,0);assert.equal(f.ctx.counts.status,0);});
test('unknown action cannot add reset or recovery route',async()=>{for(const action of ['reset','recovery','authorize','delete']){const f=fixture(),r=await f.api(action);assert.equal(r.status,404);noStart(f,r);}});
test('verifyActor false rejects without reader calls',async()=>{const f=fixture();f.ctx.hooks.actor=()=>false;const r=await f.api();assert.equal(r.status,403);assert.equal(f.ctx.counts.status,0);noStart(f,r);});
test('verifyActor truthy is not positive identity proof',async()=>{const f=fixture();f.ctx.hooks.actor=()=>({verified:true});const r=await f.api();assert.equal(r.status,403);noStart(f,r);});
test('verifyActor thrown secret has fixed projection',async()=>{const f=fixture();f.ctx.hooks.actor=()=>{throw Object.assign(new Error(secret),{code:'private_chat_oauth_state_invalid'});};const r=await f.api();assert.equal(r.status,403);noSecret(r);noStart(f,r);});

for(const [label,value]of [['held',held()],['busy',busy()]])for(const action of ['start','verify'])test(label+' '+action+' blocks all reader mutations and URLs',async()=>{const f=fixture();f.ctx.states['2001']=value;const r=await f.api(action);assertBlocked(r,label);noStart(f,r);assert.equal(f.ctx.counts.status,1);});
test('unconfigured is blocked without falsely claiming unknown refresh',async()=>{const f=fixture();f.ctx.states['2001']=unconfigured();const r=await f.api();assert.equal(r.body.code,'private_chat_auth_not_configured');assert.notEqual(r.body.status,'recovery_required');noStart(f,r);});
const badStatuses=[null,[],{},normal(false),normal(true)].filter(value=>value===null||Array.isArray(value)||Object.keys(value).length===0);
for(const [label,mutate]of [
  ['missing status',s=>{delete s.status;}],['missing retry',s=>{delete s.retryAllowed;}],['missing recovery',s=>{delete s.recoveryRequired;}],
  ['configured string',s=>{s.configured='true';}],['authorized string',s=>{s.authorized='false';}],['retry string',s=>{s.retryAllowed='true';}],
  ['recovery string',s=>{s.recoveryRequired='false';}],['unknown enum',s=>{s.status='ready';}],['unauthorized but held flags',s=>{s.recoveryRequired=true;}],
  ['unauthorized but retry forbidden',s=>{s.retryAllowed=false;}],['authorized contradictory',s=>{s.status='authorized';}],['unconfigured contradictory',s=>{s.status='unconfigured';}],
  ['recovery accessor',s=>{Object.defineProperty(s,'recoveryRequired',{get(){throw new Error(secret);}});}],
  ['inherited retry',s=>{delete s.retryAllowed;Object.setPrototypeOf(s,{retryAllowed:true});}],
])test('malformed status cannot start: '+label,async()=>{const f=fixture(),s=normal();mutate(s);f.ctx.states['2001']=s;const r=await f.api();assert.equal(r.status,409);noStart(f,r);noSecret(r);assert.equal(f.ctx.counts.status,1);});
for(const [index,value]of badStatuses.entries())test('nonrecord status '+index+' blocks start',async()=>{const f=fixture();f.ctx.states['2001']=value;const r=await f.api();assert.equal(r.status,409);noStart(f,r);});
test('status reader throw never exposes message, diagnostic or prefix',async()=>{const f=fixture();f.ctx.hooks.status=()=>{throw Object.assign(new Error(secret),{code:'private_chat_custom_prefix',diagnostic:{secret}});};const r=await f.api();assert.equal(r.status,409);noSecret(r);noStart(f,r);});
for(const authorized of [false,true])test('status projection ignores identity/expiry/diagnostic/getters '+authorized,async()=>{const f=fixture();let getterCalls=0;f.ctx.states['2001']={...normal(authorized),openId:secret,refreshExpiresAt:secret,verifiedAt:secret,reason:secret,extra:{secret},diagnostic:{secret}};Object.defineProperty(f.ctx.states['2001'],'metadata',{get(){getterCalls++;throw new Error(secret);}});const r=await f.api('status',f.auth(),req('GET'));assert.equal(r.status,200);assert.equal(r.body.authorization.authorized,authorized);assert.equal(getterCalls,0);for(const key of ['openId','refreshExpiresAt','verifiedAt','extra','diagnostic','metadata'])assert.equal(Object.hasOwn(r.body.authorization,key),false);noSecret(r);});
test('held status safely projects fixed enum flags and no green authorization',async()=>{const f=fixture();f.ctx.states['2001']={...held(),reason:secret,openId:secret};const r=await f.api('status',f.auth(),req('GET'));assert.equal(r.status,200);assert.equal(r.body.authorization.authorized,false);assert.equal(r.body.authorization.status,'recovery_required');assert.equal(r.body.authorization.recoveryRequired,true);assert.equal(r.body.authorization.retryAllowed,false);noSecret(r);});

test('verifyActor deadline blocks late success with no begin/cookie',async()=>{const f=fixture(),d=defer();f.ctx.hooks.actor=()=>d.promise;const pending=f.api();const r=await pending;assert.equal(r.status,403);noStart(f,r);d.resolve(true);await tick();assert.equal(r.jsonCalls,1);noStart(f,r);});
test('status deadline blocks late success with no begin/cookie',async()=>{const f=fixture(),d=defer();f.ctx.hooks.status=()=>d.promise;const r=await f.api();assert.equal(r.status,409);noStart(f,r);d.resolve(normal());await tick();assert.equal(r.jsonCalls,1);noStart(f,r);});
test('status deadline late rejection is consumed and cannot leak',async()=>{const f=fixture(),d=defer();f.ctx.hooks.status=()=>d.promise;const r=await f.api();d.reject(new Error(secret));await tick();assert.equal(r.jsonCalls,1);noStart(f,r);noSecret(r);});
test('overlapping starts while status pending only begin once',async()=>{const f=fixture(),d=defer();f.ctx.hooks.status=()=>d.promise;const first=f.api();await tick();const second=await f.api();assertBlocked(second,'busy');assert.equal(f.ctx.counts.begin,0);d.resolve(normal());assert.equal((await first).status,200);assert.equal(f.ctx.counts.begin,1);});
test('status refresh while start pending reports busy without authorizing duplicate',async()=>{const f=fixture(),d=defer();f.ctx.hooks.actor=()=>d.promise;const first=f.api();await tick();f.ctx.hooks.actor=()=>true;const status=await f.api('status',f.auth(),req('GET'));assert.equal(status.body.authorization.status,'busy');d.resolve(true);assert.equal((await first).status,200);assert.equal(f.ctx.counts.begin,1);});
test('second start and verify cannot ignore outstanding callback state',async()=>{const f=fixture();await begin(f);assertBlocked(await f.api(),'busy');f.ctx.states['2001']=normal(true);assertBlocked(await f.api('verify'),'busy');assert.equal(f.ctx.counts.begin,1);assert.equal(f.ctx.counts.verify,0);});
test('two fixed actors may start independent known-safe pending states',async()=>{const f=fixture();await begin(f,'2001');await begin(f,'2002');assert.equal(f.ctx.counts.begin,2);});
test('cross-actor state collision never overwrites first callback',async()=>{const f=fixture();f.ctx.hooks.begin=()=>({state:'pchat_shared',url:'https://accounts.feishu.cn/open-apis/authen/v1/authorize?state=pchat_shared'});await begin(f,'2001');const second=await f.api('start',f.auth('2002'));assert.equal(second.status,409);assert.equal(second.headers['Set-Cookie'],undefined);const result=await f.callback('pchat_shared');assert.equal(result.status,200);assert.equal(f.ctx.verifiedActors.at(-1).number,'2001');});
for(const url of ['https://other.invalid/?state=pchat_a','http://accounts.feishu.cn/?state=pchat_a','https://name:pass@accounts.feishu.cn/?state=pchat_a','https://accounts.feishu.cn:8443/?state=pchat_a','https://accounts.feishu.cn/?state=pchat_different'])test('untrusted authorize URL rejected '+url,async()=>{const f=fixture();f.ctx.hooks.begin=()=>({state:'pchat_a',url});const r=await f.api();assert.equal(r.status,409);assert.equal(r.body.authorizeUrl,undefined);assert.equal(r.headers['Set-Cookie'],undefined);});
for(const suffix of ['/different?state=pchat_a','/open-apis/authen/v1/authorize?state=pchat_a#fragment','/open-apis/authen/v1/authorize?state=pchat_a#','/open-apis/authen/v1/authorize?state=pchat_a&state=pchat_a','/open-apis/authen/v1/authorize?state=pchat_a&state=pchat_other'])test('fixed authorize endpoint/fragment/unique state '+suffix,async()=>{const f=fixture();f.ctx.hooks.begin=()=>({state:'pchat_a',url:'https://accounts.feishu.cn'+suffix});const r=await f.api();assert.equal(r.status,409);assert.equal(r.body.authorizeUrl,undefined);assert.equal(r.headers['Set-Cookie'],undefined);});
test('even explicit default port is not the fixed provider authority',async()=>{const f=fixture();f.ctx.hooks.begin=()=>({state:'pchat_a',url:'https://accounts.feishu.cn:443/open-apis/authen/v1/authorize?state=pchat_a'});const r=await f.api();assert.equal(r.status,409);assert.equal(r.body.authorizeUrl,undefined);});
test('invalid reader state never gets cookie or URL',async()=>{const f=fixture();f.ctx.hooks.begin=()=>({state:'../../'+secret,url:'https://accounts.feishu.cn/'});const r=await f.api();assert.equal(r.status,409);assert.equal(r.headers['Set-Cookie'],undefined);noSecret(r);});

test('normal verify returns only strict proof and boolean sample',async()=>{const f=fixture();f.ctx.states['2001']=normal(true);f.ctx.hooks.verify=()=>({verified:true,sampleAvailable:true,verifiedAt:secret,chatId:secret,diagnostic:{secret}});const r=await f.api('verify');assert.equal(r.status,200);assert.deepEqual(r.body.verification,{verified:true,sampleAvailable:true});noSecret(r);assert.equal(f.ctx.counts.status,2);});
test('unauthorized cannot invoke reader verify',async()=>{const f=fixture(),r=await f.api('verify');assert.equal(r.status,409);assert.equal(f.ctx.counts.verify,0);});
for(const value of [null,[],{},true,{verified:false,sampleAvailable:true},{verified:'true',sampleAvailable:false},{verified:true,sampleAvailable:'false'},{verified:true}])test('malformed verification '+JSON.stringify(value)+' cannot become verified',async()=>{const f=fixture();f.ctx.states['2001']=normal(true);f.ctx.hooks.verify=()=>value;const r=await f.api('verify');assert.equal(r.status,409);assert.equal(r.body.verification,undefined);assert.equal(r.body.retryAllowed,false);});
test('post-verify durable hold overrides a positive raw verification',async()=>{const f=fixture();f.ctx.states['2001']=normal(true);f.ctx.hooks.verify=()=>{f.ctx.states['2001']=held();return {verified:true,sampleAvailable:true};};assertBlocked(await f.api('verify'));});
test('verify throw plus status hold gets held precedence without secret',async()=>{const f=fixture();f.ctx.states['2001']=normal(true);f.ctx.hooks.verify=()=>{f.ctx.states['2001']=held();throw new Error(secret);};const r=await f.api('verify');assertBlocked(r);noSecret(r);});
test('begin throw plus status hold gets held precedence without secret',async()=>{const f=fixture();f.ctx.hooks.begin=()=>{f.ctx.states['2001']=held();throw new Error(secret);};const r=await f.api();assertBlocked(r);assert.equal(r.headers['Set-Cookie'],undefined);noSecret(r);});
for(const code of ['private_chat_authorization_held','private_chat_authorization_busy','private_chat_oauth_state_invalid','private_chat_custom_leak',secret])test('fixed public error whitelist '+code,async()=>{const f=fixture();f.ctx.hooks.begin=()=>{throw Object.assign(new Error(secret),{code,diagnostic:{secret}});};const r=await f.api();assert.equal(r.status,409);noSecret(r);assert.equal(r.body.authorizeUrl,undefined);assert.equal(r.headers['Set-Cookie'],undefined);});

test('normal matched callback completes once and preserves page/CSP',async()=>{const f=fixture(),state=await begin(f),r=await f.callback(state);assert.equal(r.handled,true);assert.equal(r.status,200);assert.equal(f.ctx.counts.complete,1);assert.equal(f.ctx.completeInput.cookieState,state);assert.equal(f.ctx.completeInput.code,'toy_code');assert.match(r.headers['Content-Security-Policy'],/default-src 'none'/u);assert.match(r.headers['Set-Cookie'],/Max-Age=0/u);assert.equal(r.endCalls,1);});
test('unknown non-pchat callback remains available for other handlers',async()=>{const f=fixture(),r=await f.callback('coach_toy');assert.equal(r.handled,false);assert.equal(r.endCalls,0);assert.equal(r.headers['Set-Cookie'],undefined);assert.equal(f.ctx.counts.status,0);});
test('unknown pchat is claimed but does not probe another reader or invite retry',async()=>{const f=fixture(),r=await f.callback('pchat_unknown');assert.equal(r.handled,true);assert.equal(r.status,409);assert.equal(f.ctx.counts.complete,0);assert.equal(f.ctx.counts.status,0);assert.doesNotMatch(r.html,/重新发起|再重新授权|请稍后重试/u);});
for(const cause of ['cancel','expired','wrongmethod','clockrollback','clocknan','sourcefail','statusfail'])test('matched callback failure held precedence '+cause,async()=>{const f=fixture(),state=await begin(f);f.ctx.states['2001']=held();let request=req('GET',{cookie:'live_private_chat_oauth_state='+state}),params={};if(cause==='cancel')params.error=secret;if(cause==='expired')f.ctx.at+=600001;if(cause==='wrongmethod')request.method='POST';if(cause==='clockrollback')f.ctx.at-=1;if(cause==='clocknan')f.ctx.at=NaN;if(cause==='sourcefail')f.ctx.hooks.actor=()=>{throw new Error(secret);};if(cause==='statusfail'){let reads=0;f.ctx.hooks.status=()=>{if(++reads===1)throw new Error(secret);return held();};}const r=await f.callback(state,params,request);assert.equal(r.status,409);assert.match(r.html,/结果待核验/u);assert.equal(f.ctx.counts.complete,0);assert.doesNotMatch(r.html,/重新发起|再重新授权/u);noSecret(r);});
test('callback complete raw error cannot reflect message or diagnostic',async()=>{const f=fixture(),state=await begin(f);f.ctx.hooks.complete=()=>{throw Object.assign(new Error(secret),{code:'private_chat_custom_leak',diagnostic:{secret}});};const r=await f.callback(state);assert.equal(r.status,409);noSecret(r);assert.doesNotMatch(r.html,/请稍后重试|重新发起/u);});
test('post-complete unknown hold overrides old state error',async()=>{const f=fixture(),state=await begin(f);f.ctx.hooks.complete=()=>{f.ctx.states['2001']=held();throw Object.assign(new Error(secret),{code:'private_chat_oauth_state_invalid'});};const r=await f.callback(state);assert.equal(r.status,409);assert.match(r.html,/结果待核验/u);noSecret(r);});
for(const value of [undefined,null,true,{},[],{authorized:false},{authorized:'true'},{authorized:true,recoveryRequired:true},{authorized:true,retryAllowed:false},{authorized:true,status:'busy'},{authorized:true,status:secret},{authorized:true,configured:false}])test('callback incomplete/contradictory result rejected '+JSON.stringify(value),async()=>{const f=fixture(),state=await begin(f);f.ctx.hooks.complete=()=>value;const r=await f.callback(state);assert.equal(r.status,409);noSecret(r);assert.doesNotMatch(r.html,/<h1>考核私聊授权完成/u);});
test('callback malicious accessor cannot hide recovery flag',async()=>{const f=fixture(),state=await begin(f);f.ctx.hooks.complete=()=>Object.defineProperty({authorized:true},'recoveryRequired',{get(){throw new Error(secret);}});const r=await f.callback(state);assert.equal(r.status,409);noSecret(r);});
test('callback inherited contradictory flag cannot become success',async()=>{const f=fixture(),state=await begin(f);f.ctx.hooks.complete=()=>Object.assign(Object.create({retryAllowed:false}),{authorized:true});const r=await f.callback(state);assert.equal(r.status,409);});
test('callback positive result must still read back authorized full safe status',async()=>{const f=fixture(),state=await begin(f);f.ctx.hooks.complete=()=>({authorized:true});const r=await f.callback(state);assert.equal(r.status,409);assert.equal(f.ctx.counts.complete,1);});
test('callback missing complete flags cannot rely on later good status',async()=>{const f=fixture(),state=await begin(f);f.ctx.hooks.complete=()=>{f.ctx.states['2001']=normal(true);return {authorized:true};};const r=await f.callback(state);assert.equal(r.status,409);assert.equal(f.ctx.counts.complete,1);});
test('callback complete contradictory enum cannot rely on later good status',async()=>{const f=fixture(),state=await begin(f);f.ctx.hooks.complete=()=>{f.ctx.states['2001']=normal(true);return {...normal(true),status:'unauthorized'};};const r=await f.callback(state);assert.equal(r.status,409);assert.equal(f.ctx.counts.complete,1);});
test('callback result positive plus post status held is not a success page',async()=>{const f=fixture(),state=await begin(f);f.ctx.hooks.complete=()=>{f.ctx.states['2001']=held();return {authorized:true};};const r=await f.callback(state);assert.equal(r.status,409);assert.match(r.html,/结果待核验/u);});
test('double callback does not exchange a code twice',async()=>{const f=fixture(),state=await begin(f),d=defer();f.ctx.hooks.complete=()=>d.promise;const first=f.callback(state);await tick();const second=await f.callback(state);assert.equal(second.status,409);assert.equal(f.ctx.counts.complete,1);f.ctx.states['2001']=normal(true);d.resolve(normal(true));assert.equal((await first).status,200);assert.equal(f.ctx.counts.complete,1);});
test('pending callback blocks concurrent start until its result is checked',async()=>{const f=fixture(),state=await begin(f),d=defer();f.ctx.hooks.complete=()=>d.promise;const callback=f.callback(state);await tick();assertBlocked(await f.api(),'busy');assert.equal(f.ctx.counts.begin,1);f.ctx.states['2001']=normal(true);d.resolve(normal(true));await callback;});
test('callback source verification deadline preserves state single-use and zero completion',async()=>{const f=fixture(),state=await begin(f),d=defer();f.ctx.hooks.actor=()=>d.promise;const r=await f.callback(state);assert.equal(r.status,409);assert.equal(f.ctx.counts.complete,0);d.resolve(true);await tick();assert.equal(r.endCalls,1);assert.equal(f.ctx.counts.complete,0);assert.equal((await f.callback(state)).status,409);});
test('callback status deadline preserves state single-use and zero completion',async()=>{const f=fixture(),state=await begin(f),d=defer();f.ctx.hooks.status=()=>d.promise;const r=await f.callback(state);assert.equal(r.status,409);assert.equal(f.ctx.counts.complete,0);d.resolve(normal());await tick();assert.equal(r.endCalls,1);assert.equal(f.ctx.counts.complete,0);});
test('TTL exactly 600000 accepted but 600001 blocked before code exchange',async()=>{for(const [elapsed,expected]of [[600000,200],[600001,409]]){const f=fixture(),state=await begin(f);f.ctx.at+=elapsed;const r=await f.callback(state);assert.equal(r.status,expected);assert.equal(f.ctx.counts.complete,expected===200?1:0);}});
test('source/status delays cannot carry callback beyond TTL',async()=>{const f=fixture(),state=await begin(f);f.ctx.hooks.status=()=>{f.ctx.at=NOW+600001;return normal();};const r=await f.callback(state);assert.equal(r.status,409);assert.equal(f.ctx.counts.complete,0);});

test('status at exactly 600000 keeps known pre-POST pending busy',async()=>{const f=fixture();await begin(f);f.ctx.at+=600000;const r=await f.api('status',f.auth(),req('GET'));assert.equal(r.status,200);assert.equal(r.body.authorization.status,'busy');assert.equal(r.body.authorization.retryAllowed,false);assert.equal(f.ctx.counts.begin,1);});
test('status at 600001 expires only healthy local pre-POST pending',async()=>{const f=fixture();await begin(f);f.ctx.at+=600001;const r=await f.api('status',f.auth(),req('GET'));assert.equal(r.status,200);assert.equal(r.body.authorization.status,'unauthorized');assert.equal(r.body.authorization.retryAllowed,true);assert.equal(f.ctx.counts.begin,1);assert.equal((await f.api()).status,200);assert.equal(f.ctx.counts.begin,2);});
test('authorized healthy status may expire stale local URL without verifying or exchanging',async()=>{const f=fixture();await begin(f);f.ctx.states['2001']=normal(true);f.ctx.at+=600001;const r=await f.api('status',f.auth(),req('GET'));assert.equal(r.body.authorization.status,'authorized');assert.equal(f.ctx.counts.complete,0);assert.equal(f.ctx.counts.verify,0);assert.equal(f.ctx.counts.begin,1);});
test('held status never clears expired local pending state',async()=>{const f=fixture(),state=await begin(f);f.ctx.at+=600001;f.ctx.states['2001']=held();const r=await f.api('status',f.auth(),req('GET'));assert.equal(r.body.authorization.status,'recovery_required');const count=f.ctx.counts.status;const callback=await f.callback(state);assert.equal(callback.status,409);assert.equal(f.ctx.counts.status,count+1);assert.equal(f.ctx.counts.complete,0);assert.equal(f.ctx.counts.begin,1);});
test('busy and unconfigured states also never clear expired local pending',async()=>{for(const value of [busy(),unconfigured()]){const f=fixture(),state=await begin(f);f.ctx.at+=600001;f.ctx.states['2001']=value;const r=await f.api('status',f.auth(),req('GET'));assert.equal(r.body.authorization.status,value.status);const count=f.ctx.counts.status;await f.callback(state);assert.equal(f.ctx.counts.status,count+1);assert.equal(f.ctx.counts.complete,0);}});
test('invalid or rolled-back status clock does not expire pending or call begin',async()=>{for(const value of [NaN,-1,NOW-1,Number.MAX_SAFE_INTEGER+1]){const f=fixture(),state=await begin(f);f.ctx.at=value;const r=await f.api('status',f.auth(),req('GET'));assert.equal(r.status,409);assert.equal(r.body.retryAllowed,false);assert.equal(f.ctx.counts.begin,1);f.ctx.at=NOW;assert.equal((await f.callback(state)).status,200);assert.equal(f.ctx.counts.complete,1);}});
test('healthy status cannot expire another actor without that reader snapshot',async()=>{const f=fixture(),state=await begin(f,'2002');f.ctx.states['2002']=held();f.ctx.at+=600001;assert.equal((await f.api('status',f.auth('2001'),req('GET'))).body.authorization.status,'unauthorized');const count=f.ctx.counts.status;await f.callback(state);assert.equal(f.ctx.counts.status,count+1);assert.equal(f.ctx.counts.complete,0);});
test('ongoing callback stays busy despite healthy snapshot and elapsed URL TTL',async()=>{const f=fixture(),state=await begin(f),d=defer();f.ctx.hooks.complete=()=>d.promise;const completion=f.callback(state);await tick();f.ctx.at+=600001;const status=await f.api('status',f.auth(),req('GET'));assert.equal(status.body.authorization.status,'busy');assertBlocked(await f.api(),'busy');assert.equal(f.ctx.counts.complete,1);assert.equal(f.ctx.counts.begin,1);f.ctx.states['2001']=normal(true);d.resolve(normal(true));assert.equal((await completion).status,200);});

test('old wrapper held start counterexample stays demonstrably false',async()=>{const f=fixture({},oldFactory);f.ctx.states['2001']=held();const r=await f.api();assert.equal(r.status,200);assert.equal(f.ctx.counts.begin,1);assert.equal(f.ctx.counts.status,0);assert.equal(typeof r.body.authorizeUrl,'string');});
test('old wrapper status metadata counterexample stays demonstrably false',async()=>{const f=fixture({},oldFactory);f.ctx.states['2001']={...normal(true),openId:secret,refreshExpiresAt:secret,reason:secret};const r=await f.api('status',f.auth(),req('GET'));assert.equal(JSON.stringify(r.body).includes(secret),true);});
test('old wrapper error prefix reflection remains original evidence',async()=>{const f=fixture({},oldFactory);f.ctx.hooks.begin=()=>{throw Object.assign(new Error(secret),{code:'private_chat_custom_leak'});};assert.equal((await f.api()).body.error,secret);});
test('old callback consumed-state failure has no held status check and invites restart',async()=>{const f=fixture({},oldFactory),state=await begin(f);f.ctx.states['2001']=held();const r=await f.callback(state,{error:'access_denied'});assert.equal(f.ctx.counts.status,0);assert.match(r.html,/重新授权/u);assert.equal(f.ctx.counts.complete,0);});
